services:
  - type: web
    name: eduvault
    runtime: python
    plan: free
    rootDir: eduvault
    buildCommand: ./build.sh
    startCommand: gunicorn eduvault.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
