# Generated by Django 6.0.3 on 2026-04-05 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('cycle', 'Cycle Staff'), ('branch', 'Branch Staff')], max_length=10)),
                ('cycle', models.CharField(blank=True, choices=[('P', 'P Cycle'), ('C', 'C Cycle')], max_length=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.branche')),
            ],
        ),
    ]
