# Generated by Django 6.0.3 on 2026-04-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role_type',
            field=models.CharField(choices=[('cycle', 'Cycle Staff'), ('branch', 'Branch Staff'), ('hod', 'HOD')], max_length=10),
        ),
    ]
