# Generated by Django 6.0.3 on 2026-04-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
