# Generated by Django 6.0.3 on 2026-03-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
