# Generated by Django 6.0.3 on 2026-04-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='password',
        ),
    ]
