# Generated by Django 6.0.3 on 2026-03-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_scheme'),
        ('staff', '0003_staff_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cycle',
            field=models.CharField(blank=True, choices=[('P', 'P Cycle'), ('C', 'C Cycle')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='role_type',
            field=models.CharField(choices=[('cycle', 'Cycle Staff'), ('branch', 'Branch Staff')], default='branch', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.branche'),
        ),
    ]
