# Generated by Django 6.0.3 on 2026-03-13 17:00

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('branche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.branche', verbose_name='Branch')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject')),
            ],
        ),
    ]
