# Generated by Django 6.0.3 on 2026-03-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='scheme',
        ),
    ]
