# Generated by Django 6.0.3 on 2026-03-07 17:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_branche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
