# Generated by Django 6.0.3 on 2026-03-14 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_scheme'),
        ('materials', '0002_remove_material_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
