# Generated by Django 6.0.3 on 2026-03-19 13:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_subject_delete_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
