# Generated by Django 6.0.3 on 2026-03-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_scheme'),
        ('materials', '0004_alter_material_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.branche'),
        ),
        migrations.AddField(
            model_name='material',
            name='cycle',
            field=models.CharField(blank=True, choices=[('P', 'P Cycle'), ('C', 'C Cycle')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='CycleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('P', 'P'), ('C', 'C')], max_length=1)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.branche')),
            ],
        ),
    ]
