# Generated by Django 6.0.3 on 2026-03-24 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_scheme'),
        ('materials', '0005_material_branch_material_cycle_cycleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleassignment',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academics.scheme'),
            preserve_default=False,
        ),
    ]
