# Generated by Django 6.0.3 on 2026-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_diploma',
            field=models.BooleanField(default=False),
        ),
    ]
