# Generated by Django 6.0.3 on 2026-03-07 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='branch',
            new_name='branche',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
