# Generated by Django 6.0.3 on 2026-03-24 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject_scheme'),
        ('students', '0002_alter_student_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='branche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.branche'),
        ),
    ]
