# Generated by Django 6.0.3 on 2026-03-07 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_branche_options'),
        ('students', '0003_alter_student_branche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.branche', verbose_name='Branch'),
        ),
    ]
