# Generated by Django 6.0.3 on 2026-03-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='Branche',
        ),
    ]
