# Generated by Django 6.0.3 on 2026-03-07 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_rename_branch_branche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branche',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
    ]
